apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: time-service
spec:
  selector:
    app: time-python
  ports:
  - protocol: "TCP"
    port: 6001
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: hello-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: time-python
  template:
    metadata:
      labels:
        app: time-python
    spec:
      containers:
      - name: time-python
        image: time-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000